[platformio]
default_envs = romeo_leonardo

[env:romeo_leonardo]
platform = atmelavr
board = leonardo
framework = arduino
monitor_speed = 115200
upload_speed = 57600
lib_deps =
  waspinator/AccelStepper@^1.64
  bogde/HX711@^0.7.5
